version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: edu_exams
    command: /scripts/run_django.sh
    env_file:
      - .env
    volumes:
      - .:/project
    ports:
      - "8000:8000"
      - "80:80"
    depends_on:
      - edu_exams_db

  edu_exams_db:
    image: postgres
    volumes:
      - edu_exams_volume:/var/lib/postgresql/data/
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_DB=edu_exams
      - POSTGRES_USER=edu_exams
      - POSTGRES_PASSWORD=edu_exams

volumes:
  edu_exams_volume:
