version: "3.8"

services:
  edu_exams_db:
    image: postgres
    volumes:
      - edu_exams_volume:/var/lib/postgresql/data/
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_DB=edu_exams
      - POSTGRES_USER=edu_exams
      - POSTGRES_PASSWORD=edu_exams

volumes:
  edu_exams_volume:
