# Generated by Django 4.0.6 on 2023-03-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_rename_ordinaryquestionfilemodel_ordinaryquestionfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='hours_to_pass',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='minutes_to_pass',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='seconds_to_pass',
            field=models.SmallIntegerField(null=True),
        ),
    ]
