# Generated by Django 4.0.6 on 2023-03-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_hours_to_pass_exam_minutes_to_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
