# Generated by Django 4.0.6 on 2023-04-21 10:42

import app.exams.contants
import app.exams.utils.file_upload
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_studentexam_end_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalQuestion',
            fields=[
                ('header', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('right_answer_points', models.SmallIntegerField(null=True)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.exam')),
            ],
            options={
                'verbose_name': 'Вопрос с ответом пользователя',
                'verbose_name_plural': 'Вопроcы с ответами пользователей',
            },
        ),
        migrations.CreateModel(
            name='OriginalQuestionUserAnswer',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.originalquestion')),
                ('student_exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.studentexam')),
            ],
            options={
                'verbose_name': 'Ответ пользователя на вопрос с одним вариантом ответа',
                'verbose_name_plural': 'Ответы пользователя на вопрос с одним вариантом ответа',
            },
        ),
        migrations.CreateModel(
            name='OriginalQuestionFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'TYPE_IMAGE')], default=app.exams.contants.FileType['TYPE_IMAGE'])),
                ('file', models.FileField(upload_to=app.exams.utils.file_upload.file_ordinary_question_upload)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='exams.originalquestion')),
            ],
            options={
                'verbose_name': 'Файл оригинального вопроса',
                'verbose_name_plural': 'Файлы оригинальных вопросов',
            },
        ),
        migrations.CreateModel(
            name='OriginalQuestionAnswer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.originalquestion')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос с ответом пользователя',
                'verbose_name_plural': 'Ответы на вопрос с ответами пользователей',
            },
        ),
    ]
