# Generated by Django 4.0.6 on 2023-04-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_originalquestion_originalquestionuseranswer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='originalquestionfile',
            options={'verbose_name': 'Файлы вопросов с ответами пользователей', 'verbose_name_plural': 'Файлы вопросов с ответами пользователей'},
        ),
    ]
