# Generated by Django 4.0.6 on 2023-04-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_originalquestionfile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='originalquestionuseranswer',
            options={'verbose_name': 'Ответ пользователя на вопрос c ответом пользователя', 'verbose_name_plural': 'Ответы пользователей на вопросы c ответами пользователей'},
        ),
    ]
