# Generated by Django 4.0.6 on 2023-04-22 16:58

import app.exams.contants
import app.exams.utils.file_upload
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_originalbetweenquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleQuestion',
            fields=[
                ('header', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.exam')),
            ],
            options={
                'verbose_name': 'Вопрос с множеством вариантов ответов',
                'verbose_name_plural': 'Вопросы с множеством вариантов ответов',
            },
        ),
        migrations.CreateModel(
            name='MultipleQuestionAnswer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('right_answer_points', models.SmallIntegerField(null=True)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.multiplequestion')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос с множествами вариантами ответов',
                'verbose_name_plural': 'Ответ на вопросы с множествами вариантами ответов',
            },
        ),
        migrations.CreateModel(
            name='MultipleQuestionUserAnswer',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.multiplequestionanswer')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.multiplequestion')),
                ('student_exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.studentexam')),
            ],
            options={
                'verbose_name': 'Ответ пользователя на вопрос с одним вариантом ответа',
                'verbose_name_plural': 'Ответы пользователя на вопрос с одним вариантом ответа',
            },
        ),
        migrations.CreateModel(
            name='MultipleQuestionFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'TYPE_IMAGE')], default=app.exams.contants.FileType['TYPE_IMAGE'])),
                ('file', models.FileField(upload_to=app.exams.utils.file_upload.file_multiple_question_upload)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='exams.multiplequestion')),
            ],
            options={
                'verbose_name': 'Файл вопроса со множеством вариантов ответов',
                'verbose_name_plural': 'Файлы вопросов со множествами вариантов ответов',
            },
        ),
        migrations.CreateModel(
            name='MultipleQuestionAnswerFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'TYPE_IMAGE')], default=app.exams.contants.FileType['TYPE_IMAGE'])),
                ('file', models.FileField(upload_to=app.exams.utils.file_upload.file_multiple_question_upload)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='exams.multiplequestionanswer')),
            ],
            options={
                'verbose_name': 'Файл ответа на вопрос со множеством вариантов ответов',
                'verbose_name_plural': 'Файлы ответов на вопросы со множеством вариантов ответов',
            },
        ),
    ]
