# Generated by Django 4.0.6 on 2023-05-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_originalbetweenquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalquestionbetweenansweritem',
            name='text_end',
            field=models.TextField(blank=True, null=True),
        ),
    ]
