# Generated by Django 4.0.6 on 2023-04-22 07:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_originalbetweenquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalquestionbetweenansweritem',
            name='student_exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.studentexam'),
        ),
        migrations.CreateModel(
            name='OriginalQuestionBetweenUserAnswerItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.originalquestionbetweenansweritem')),
            ],
            options={
                'verbose_name': 'Ответ пользователя на элемент вопроса со вписыванием между текстом',
                'verbose_name_plural': 'Ответы пользователей на элементы вопросов со вписыванием между текстом',
            },
        ),
    ]
