# Generated by Django 4.0.6 on 2023-04-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_originalbetweenquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalquestionbetweenansweritem',
            name='order_index',
            field=models.SmallIntegerField(null=True),
        ),
    ]
