# Generated by Django 4.0.6 on 2023-05-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_originalquestionbetweenansweritem_text_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonquestion',
            name='option',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordinaryquestion',
            name='option',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originalbetweenquestion',
            name='option',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originalquestion',
            name='option',
            field=models.TextField(blank=True, null=True),
        ),
    ]
