# Generated by Django 4.0.6 on 2023-05-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_comparisonquestion_option_ordinaryquestion_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonquestion',
            name='option',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ordinaryquestion',
            name='option',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='originalbetweenquestion',
            name='option',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='originalquestion',
            name='option',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='originalquestionbetweenansweritem',
            name='text_answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='originalquestionbetweenansweritem',
            name='text_end',
            field=models.TextField(null=True),
        ),
    ]
