# Generated by Django 4.0.6 on 2023-03-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_ordinaryquestionuseranswer_student_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comparisonquestion',
            options={'verbose_name': 'Вопрос с сопоставлением ответов', 'verbose_name_plural': 'Вопросы с сопоставлением ответов'},
        ),
        migrations.AlterModelOptions(
            name='comparisonquestionoption',
            options={'verbose_name': 'Опция вопроса с сопоставлением ответа', 'verbose_name_plural': 'Опции вопроса с сопоставлением ответа'},
        ),
        migrations.AlterModelOptions(
            name='comparisonquestionoptionanswer',
            options={'verbose_name': 'Ответ на опцию вопроса с сопоставлением', 'verbose_name_plural': 'Ответы на опцию вопроса с сопоставлением'},
        ),
        migrations.AlterModelOptions(
            name='comparisonquestionuseranswer',
            options={'verbose_name': 'Ответ пользователя на вопрос с сопоставлением ответов', 'verbose_name_plural': 'Ответы пользователя на вопрос с сопоставлением ответов'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Экзамен', 'verbose_name_plural': 'Экзамены'},
        ),
        migrations.AlterModelOptions(
            name='ordinaryquestion',
            options={'verbose_name': 'Вопрос с одним вариантом ответа', 'verbose_name_plural': 'Вопросы с одним вариантом ответа'},
        ),
        migrations.AlterModelOptions(
            name='ordinaryquestionanswer',
            options={'verbose_name': 'Ответ на вопрос с одним вариантом ответа', 'verbose_name_plural': 'Ответы на вопрос с одним вариантом ответа'},
        ),
        migrations.AlterModelOptions(
            name='ordinaryquestionuseranswer',
            options={'verbose_name': 'Ответ пользователя на вопрос с одним вариантом ответа', 'verbose_name_plural': 'Ответы пользователя на вопрос с одним вариантом ответа'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Образовательное учреждение', 'verbose_name_plural': 'Образовательные учреждения'},
        ),
        migrations.AlterModelOptions(
            name='studentexam',
            options={'verbose_name': 'Экзамен студента', 'verbose_name_plural': 'Экзамены студента'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
    ]
