# Generated by Django 4.0.6 on 2023-03-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_studentexam_user_studentexam_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonquestionoptionanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.comparisonquestion'),
        ),
    ]
