# Generated by Django 4.0.6 on 2023-03-25 15:38

from django.db import migrations, models
import django.db.models.deletion
import exams.contants
import exams.utils.file_upload
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_comparisonquestionfilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonquestionfilemodel',
            name='file',
            field=models.FileField(upload_to=exams.utils.file_upload.file_comparison_question_upload),
        ),
        migrations.CreateModel(
            name='OrdinaryQuestionAnswerFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'TYPE_IMAGE')], default=exams.contants.FileType['TYPE_IMAGE'])),
                ('file', models.FileField(upload_to=exams.utils.file_upload.file_ordinary_answer_upload)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='exams.ordinaryquestionanswer')),
            ],
            options={
                'verbose_name': 'Файл ответа на обычный вопрос',
                'verbose_name_plural': 'Файлы ответов на обычные вопрос',
            },
        ),
    ]
