# Generated by Django 4.0.6 on 2023-03-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_comparisonquestionoptionanswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonquestionoption',
            name='right_answer_points',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ordinaryquestion',
            name='right_answer_points',
            field=models.SmallIntegerField(null=True),
        ),
    ]
